# Generated by Django 5.2.8 on 2025-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
