# Generated by Django 5.2.8 on 2025-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='momo_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='momo_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
