# Generated by Django 5.2.8 on 2025-11-16 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'size'], 'verbose_name': 'Biến thể sản phẩm', 'verbose_name_plural': 'Biến thể sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('30cm', '30cm'), ('60cm', '60cm'), ('90cm', '90cm')], max_length=20, verbose_name='Kích thước'),
        ),
    ]
