# Generated by Django 5.2.8 on 2026-05-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_add_color'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE products DROP COLUMN size;",
            reverse_sql="ALTER TABLE products ADD COLUMN size VARCHAR(50) NOT NULL DEFAULT '30cm';",
        ),
    ]
