# Generated by Django 5.2.12 on 2026-05-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0007_drop_product_size_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Danh mục'),
            preserve_default=False,
        ),
    ]
