# Generated by Django 5.2.8 on 2026-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_allow_anonymous_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=30000, max_digits=15),
        ),
    ]
