# Generated by Django 5.2.8 on 2026-03-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_automatedorder_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email khách hàng (nếu có)', max_length=254),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Số điện thoại khách hàng', max_length=20),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Khách hàng'), ('assistant', 'AI')], help_text='Vai trò người gửi', max_length=10)),
                ('content', models.TextField(help_text='Nội dung tin nhắn')),
                ('products', models.TextField(blank=True, help_text='JSON danh sách sản phẩm (nếu có)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Tin nhắn đã bị xóa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.conversationsession')),
            ],
            options={
                'verbose_name': 'Tin nhắn hội thoại',
                'verbose_name_plural': 'Tin nhắn hội thoại',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='ai_agent_co_convers_13d0f3_idx'), models.Index(fields=['role', 'created_at'], name='ai_agent_co_role_f33eba_idx')],
            },
        ),
    ]
