# Generated by Django 5.2.8 on 2026-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_conversationsession_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='customer_id',
            field=models.CharField(blank=True, help_text='ID khách hàng vãng lai (auto-generated)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email khách hàng (nếu là vãng lai)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='SĐT khách hàng (nếu là vãng lai)', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
