# Generated by hand for safe chat message normalization

import json
from django.db import migrations, models
import django.db.models.deletion


def _normalize_role(raw_role):
    role = (raw_role or '').strip().lower()
    if role in {'user', 'assistant', 'admin'}:
        return role
    return 'assistant'


def backfill_messages_from_context(apps, schema_editor):
    ConversationSession = apps.get_model('ai_agent', 'ConversationSession')
    ConversationMessage = apps.get_model('ai_agent', 'ConversationMessage')

    batch = []
    batch_size = 500

    for session in ConversationSession.objects.all().iterator():
        # Skip if session already has normalized messages
        if ConversationMessage.objects.filter(conversation_id=session.id).exists():
            continue

        try:
            ctx = json.loads(session.context) if session.context else {}
        except json.JSONDecodeError:
            ctx = {}

        messages = ctx.get('messages', [])
        if not isinstance(messages, list):
            continue

        for msg in messages:
            if not isinstance(msg, dict):
                continue

            products = msg.get('products', [])
            if not isinstance(products, list):
                products = []

            batch.append(
                ConversationMessage(
                    conversation_id=session.id,
                    role=_normalize_role(msg.get('role')),
                    content=str(msg.get('content', '')).strip(),
                    products=json.dumps(products, ensure_ascii=False),
                )
            )

            if len(batch) >= batch_size:
                ConversationMessage.objects.bulk_create(batch, batch_size=batch_size)
                batch = []

    if batch:
        ConversationMessage.objects.bulk_create(batch, batch_size=batch_size)


def noop_reverse(apps, schema_editor):
    # Keep normalized messages when rolling back this migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_conversationsession_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Khách hàng'), ('assistant', 'AI'), ('admin', 'Quản trị viên')], max_length=20)),
                ('content', models.TextField()),
                ('products', models.TextField(blank=True, help_text='JSON array of products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.conversationsession')),
            ],
            options={
                'verbose_name': 'Tin nhắn hội thoại',
                'verbose_name_plural': 'Tin nhắn hội thoại',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['conversation', 'created_at'], name='ai_agent_co_convers_13d0f3_idx'),
                    models.Index(fields=['role', 'created_at'], name='ai_agent_co_role_f33eba_idx'),
                ],
            },
        ),
        migrations.RunPython(backfill_messages_from_context, noop_reverse),
    ]
